site_name: AM2H_Core
site_url: https://github.com/AM2H-Development/AM2H_Core
nav:
    - Home: index.md
    - Hardware: hardware.md
        - Core:
        - SHT21:
    - About: about.md
    - Tools:

theme: readthedocs
