site_name: AM2H_Core
site_url: https://github.com/AM2H-Development/AM2H_Core
nav:
    - Home: index.md
    - About: about.md
    - Tools:
        - md Cheat-Sheet: markdown-cheat-sheet.md
theme: readthedocs
