site_name: AM2H_Core
site_url: https://github.com/AM2H-Development/AM2H_Core
nav:
    - Home: index.md
    - Hardware:
        - Core: hardware.md
        - Plugins: plugins.md
    - About:
        - About: about.md
    - Tools:
        - test: tools.md

theme: readthedocs
